version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your Python dependencies (e.g., `requirements.txt` or `pyproject.toml`)
    schedule:
      interval: "weekly" # Check for updates weekly
    ignore:
      - dependency-name: "requests"
        versions: ["2.24.0"] # Example to ignore specific versions of a dependency

  - package-ecosystem: "docker"
    directory: "/" # Location of your Dockerfile
    schedule:
      interval: "weekly" # Check for updates weekly

  - package-ecosystem: "github-actions"
    directory: ".github/workflows" # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly" # Check for updates weekly
