apiVersion: v1
kind: Service
metadata:
  name: ssh-load-balancer
spec:
  selector:
    app: ssh-service
  ports:
    - protocol: TCP
      port: 22
      targetPort: 2222
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter
spec:
  selector:
    app: ssh-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
