name: Integration Tests

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Load Docker images into Kind
      run: |
        IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
        kind load docker-image ghcr.io/${{ github.repository }}/ssh-server:${IMAGE_TAG}
        kind load docker-image ghcr.io/${{ github.repository }}/ssh-client:${IMAGE_TAG}

    - name: Install dependencies for integration tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest sshpass

    - name: Run integration tests
      env:
        PYTHONPATH: ./scripts
        IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      run: |
        pytest tests/integration_tests/
